"""Render data/attributes.md: everything the five attributes do, from the live GlobalSettings asset + the game's own
attribute tooltip (decomp/Tooltip.cs, "Effects Per Point") + the compiled stat expressions (decomp/CompiledDynamicExpresso.cs),
plus every skill, mythic and fortune that scales with an attribute. Run from the repo root:  python tools/attributes_md.py
"""
import json, re, os, io

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
g = json.load(io.open(os.path.join(ROOT, "data", "GlobalSettings.json"), encoding="utf-8"))
g = g[0] if isinstance(g, list) else g


def curve(nodes, x):
    pts = [(n["level"], n["mutlipler"]) for n in nodes]
    if x <= pts[0][0]:
        return pts[0][1]
    for (a, va), (b, vb) in zip(pts, pts[1:]):
        if a <= x <= b:
            return va + (vb - va) * (x - a) / (b - a)
    return pts[-1][1]


def curve_text(nodes):
    return ", ".join(f"{int(n['level'])} → {n['mutlipler']:g}%" for n in nodes)


D, C = g["DodgeChanceByDodgeRating"], g["CritChanceByCritRating"]
L = []
L.append("# What every attribute does (Stolen Realm, live asset values)\n")
L.append("Generated by `tools/attributes_md.py` from `data/GlobalSettings.json`, the game's attribute tooltip code (`decomp/Tooltip.cs`) and the compiled stat expressions (`decomp/CompiledDynamicExpresso.cs`). Every formula uses `stat - 8`: the first 8 points in any attribute do nothing. Creation: five stats summing to %d, each %d–%d. Levels: +%d points per level. Player health = %g × (1 + %g%% × (level − 1)); mana = %g × (1 + %g%% × (level − 1)).\n" % (
    g["creationStatTotal"], g["creationStatMin"], g["creationStatMax"], g["NumStatsPerNewLevel"], g["HealthBase"], g["PercBaseHealthPerLevel"], g["ManaBase"], g["PercBaseManaPerLevel"]))

L.append("## Per point above 8\n")
L.append("| Attribute | Effect per point | Notes |")
L.append("|---|---|---|")
L.append(f"| **Might** | +{g['AbilityPwrPerMight']:g}% Damage & Healing (\"Ability Power\") | A separate multiplier: `(1 + additive damage bonuses) × (1 + Might%)`. Monk's Strength passive × 1.33. |")
L.append(f"| Might | +{g.get('AbilityPwrPerMightSummon', 1):g}% Summon Damage | Only matters with summons. |")
L.append(f"| Might | +{g['ArmorPercPerMight']:g}% Armor and +{g['MagicArmorPercPerMight']:g}% Magic Armor | Percent of the armour you have from gear; nothing without armour. |")
L.append(f"| **Dexterity** | +{g['CritRatingPerDex']:g} Crit Rating | Rating → crit chance curve: {curve_text(C)} (linear between). Base crit chance {g['BaseCritChance']:g}%. |")
L.append(f"| Dexterity | +{g['CritDamagePerDex']:g}% Crit Damage | Base crit damage {g['BaseCritDamage']:g}%. |")
L.append(f"| Dexterity | +1 Movement Point per {g['MovementPointPerDexInterval']:g} Dexterity (max 3) | Uses the stored value (not −8). |")
L.append(f"| **Intelligence** | +{g['ManaPerInt']:g} Max Mana and +{g['MaxManaPercPerInt']:g}% Max Mana | |")
L.append(f"| Intelligence | +1 Skill Range per {g['RangePerIntInterval']:g} Intelligence (max 3) | Uses the stored value. |")
L.append(f"| Intelligence | +{g['SummonLifePerInt']:g}% Summon Health | Only with summons. |")
L.append(f"| **Vitality** | +{g['MaxHealthPerVit']:g} Max Health and +{g['MaxHealthPercPerVit']:g}% Max Health | The percent applies to base health and the flat part. |")
L.append(f"| **Reflex** | +{g['DodgeRatingPerReflex']:g} Dodge Rating | Rating → dodge chance curve: {curve_text(D)} (linear between). Dodge chance is then capped at 75%. Flat +X% dodge from skills, items and fortunes adds on top of the curve, before the cap. |")
L.append(f"| Reflex | +{g['DodgeCounterChancePerReflex']:g}% Dodge Counter Chance (max 100%) | Chance that a dodge answers with a counter attack (a full basic attack; with two weapons, two hits). Counters need the character not Disabled and a counter left this turn. |")
L.append(f"| Reflex | +{g['OppAttackPercDmgPerReflex']:g}% Counter Attack Damage and +{g['OppAttackPercDmgPerReflex']:g}% Opportunity Attack Damage | \"Dodge Counter Damage\": a separate multiplier on counters, on top of every other bonus. Opportunist, Uncanny Evasion, Fencer's Gift and the Bone Jester items add to the same stat. |")
L.append(f"| Reflex | +1 Counter Attack per turn per {g['ExtraCounterAttacksPerReflexInterval']:g} Reflex | Base 1 per turn. The code caps the extra counters at 5 (`Mathf.Min(5, …)`); the in-game tooltip still says 3. Uses the stored value. |")
L.append(f"| Reflex (summons) | +{g['DodgeRatingPerReflexSummon']:g} Dodge Rating to your summons | |")
L.append("")

L.append("## Worked values\n")
L.append("| Stored Reflex | Dodge from rating | + 26 flat (Fencer's Finesse I/II, Dual-Wield Mastery, Survivalist I/II) | Counter chance | Counters per turn (base 1, no En Garde) |")
L.append("|---|---|---|---|---|")
for s in (30, 50, 70, 90, 110, 150):
    r = s - 8
    L.append(f"| {s} | {curve(D, r):.0f}% | {min(75, curve(D, r) + 26):.0f}% | {min(100, r):.0f}% | {1 + min(5, s // 25)} |")
L.append("")
L.append("| Stored Dexterity | Crit chance (base 2 + curve) | Crit damage (base 50 + 1.5/pt) |")
L.append("|---|---|---|")
for s in (30, 50, 70, 90):
    r = s - 8
    L.append(f"| {s} | {g['BaseCritChance'] + curve(C, r):.0f}% | {g['BaseCritDamage'] + g['CritDamagePerDex'] * r:.0f}% |")
L.append("")
L.append("Health at level 30 with Vitality V: `(535 + 5 × (V − 8)) × (1 + (V − 8)/100)` → Vitality 8: 535 · 28: 762 · 48: 1,051 · 68: 1,381. Mana at level 30 with Intelligence 8: 535.\n")

L.append("## Caps and related constants\n")
L.append("Dodge chance 75% · Damage Reduction 50% · resistances 75% (Fire 50%) · Dodge Counter Chance 100% · crit chance has no cap below 100% · " + f"{g['ArmorPerDamagePointReduction']:g} armor prevents 1 damage, at most 90% of a hit. Base Reflex constant {g['BaseReflex']:g} (unused for players). Opportunity attacks use the same Reflex damage bonus.\n")

# ---- what scales with attributes
L.append("## Skills, items and fortunes that scale with an attribute\n")
L.append("Anything with an attribute in its formula is worth more to a build that stacks that attribute. From the tree files, `mythic-items.md` and `fortunes.md`:\n")
pat = re.compile(r'Source\["(Might|Dexterity|Intelligence|Vitality|Reflex)"\]|SumOfAllAttributes|HighestStat')
rows = []
for tree in sorted(os.listdir(os.path.join(ROOT, "data", "skills"))):
    if not tree.endswith(".md") or tree in ("INDEX.md", "ACTIONS.md", "STATUSES.md", "Bard.md"):
        continue
    cur = None
    for line in io.open(os.path.join(ROOT, "data", "skills", tree), encoding="utf-8"):
        if line.startswith("### "):
            cur = re.sub(r"\s+·.*", "", line[4:].strip())
        elif cur and pat.search(line):
            attrs = sorted(set(pat.findall(line))) or ["all"]
            rows.append(("Skill", f"{cur} ({tree[:-3]})", ", ".join(a or "all/highest" for a in attrs), line.strip()[:110]))
            cur = None
for path, kind in (("mythic-items.md", "Mythic"), ("fortunes.md", "Fortune")):
    cur = None
    for line in io.open(os.path.join(ROOT, path), encoding="utf-8"):
        if line.startswith("### "):
            cur = re.split(r"\s+—", line[4:].strip())[0].strip()
        elif cur and pat.search(line):
            attrs = sorted(set(a for a in pat.findall(line) if a))
            rows.append((kind, cur, ", ".join(attrs) or "all", line.strip()[:110]))
            cur = None
L.append("| Kind | Name | Scales with | Line |")
L.append("|---|---|---|---|")
for k, n, a, ln in rows:
    L.append(f"| {k} | {n} | {a} | {ln.replace('|', '/')} |")
L.append("")
L.append("Stat-stick fortunes: Strength (Might +4→20), Celerity (Dexterity +4→20), Brilliance (Intelligence +4→20), Grace of the Rogue (Reflex +5→25), Might of the Warrior (Might +5→25), Brawler's Brew (Might +12→60, Blind each turn). Monk's Speed passive: Dexterity and Reflex +15%; Perfected Soul: all attributes + level and +10% of the highest to the others.\n")

out = os.path.join(ROOT, "data", "attributes.md")
io.open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("wrote", out, len(L), "lines,", len(rows), "scaling entries")
